[wokwi]
version=1
firmware='.pio/build/uno/firmware.hex'
elf='.pio/build/uno/firmware.elf'

[[chip]]
name = 'chip-magnet-sensor'  # To use the chip in diagram.json, add a part with "chip-inverter" type.
binary = 'chips/magnet-sensor-chip.wasm'
