[wokwi]
version=1
firmware='.pio/build/uno/firmware.hex'
elf='.pio/build/uno/firmware.elf'
gdbServerPort=3333

[[chip]]
name = 'magnet-sensor'  # To use the chip in diagram.json, add a part with "chip-chip-magnet-sensor" type.
binary = 'chips/magnet-sensor-chip.wasm'
